---
  version: "2.1"
  services:
    nginx: 
      image: nginx:latest
      container_name: reverse
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /etc/letsencrypt/:/etc/letsencrypt/
      network_mode: "service:wireguard"

    wireguard:
      image: ghcr.io/linuxserver/wireguard
      container_name: wireguard
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Nassau
        #- SERVERURL=wireguard.domain.com #optional
        - SERVERPORT=51820 #optional
        - PEERS=raspi,client #optional
        - INTERNAL_SUBNET=192.168.10.0 #optional
      volumes:
        - ./config:/config
        - /lib/modules:/lib/modules
      ports:
        - 51820:51820/udp
        - 80:80       # Nginx 
        - 443:443     # Nginx
        - 25565:25565 # Nginx L4
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv4.ip_forward=1
      restart: unless-stopped